baseURL: "https://aychen5.github.io" 
title: Annie Y. Chen
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 2 
        - name: Papers
          url: papers/
          weight: 5
        # - name: Courses
        #   url: courses/
        #  weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        - name: Blog
          url: blog/
          weight: 6

params:
    description: "Hi! I am a social data scientist/computational social scientist/quantitative researcher. For the past few years, I've been supporting public safety analytics at the CUNY Institute for State and Local Governance by building data pipelines and applying statistical/ML models to understand policing. <br><br> I'm currently looking for opportunities to make an impact in climate tech and ways to engage in environmental/sustainability efforts at any level. <br> Outside of work, you’ll almost certainly find me on a tennis court, with my nose in a good book, or painting!"
    author: Annie Chen
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "October 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","papers","blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Annie Chen
          subtitle: "Hi! I am a social data scientist / computational social scientist / quantitative researcher. I spent the past few years supporting public safety research for local government by designing studies and making sense of data using statistical/ML models. <br><br>I'm currently exploring opportunities to make an impact in climate tech and ways to engage in environmental/sustainability efforts at any level. <br><br> Outside of work, you will almost certainly find me on a tennis court, with my nose in a good book, or running a painting and crafting!"
          imageUrl: "profile-picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Tags
              url: tags/
            - name: Blog
              url: blog/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: aychen.555@gmail.com
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=l4CPMNYAAAAJ
        - name: GitHub
          url: https://github.com/aychen5
        - name: Twitter
          url: https://x.com/annie_y_chen

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Annie Chen"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2